print('chương trình trình phân loại sinh viên.')
print('nhập điểm sinh viên,',end='')
loai=input("điểm:")
if loai=='A':print("xếp loại xuất sắc")
elif loai=='B':print("xếp loại giỏi.")
elif loai=='C':print("xếp loại khá.")
elif loai=='D':print("xếp loại trung bình.")
elif loai=='E':print("xếp loại yếu.")
elif loai=='F':print("xếp loại kém.")
else:
    print("nhập sai xin mời nhập lại điểm!")